### ISSUE TITLE
cannot import name 'pygazebo' 

### ISSUE THREAD

**Issue by www2171668** [HorizonRobotics/SocialRobot#136]
Hello, I meet a problem when i test "python3 python/social_bot/envs/play_ground.py". It shows:
Traceback (most recent call last):
  File "python/social_bot/envs/play_ground.py", line 31, in <module>
    import social_bot
  File "/home/huang/Project/HIDIO/SocialRobot/python/social_bot/__init__.py", line 66, in <module>
    from . import pygazebo
ImportError: cannot import name 'pygazebo'

I think I install correctly Gazebo9.19.0 and SocialRobot. My system is Ubuntu 18.04. Package is python3.6.
I don't know how to choose Gazebo9.6 version, Is it influence the code? Thankyou.

**Comment by www2171668** [comment]
I deal with it. When I put the pkg in a Pro, It works well. I think the position influences the code.
