### ISSUE TITLE
libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

### ISSUE THREAD

**Issue by www2171668** [HorizonRobotics/SocialRobot#138]
Hello. When I run 'python3 test_simple_navigation.py'. It prints ImportError: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates. Do you know how to deal with it? Thank you.

My gazebo is 9.16.0. 

Traceback (most recent call last):
  File "test_simple_navigation.py", line 5, in <module>
    import social_bot
  File "/home/huang/Project/HIDIO/SocialRobot/python/social_bot/__init__.py", line 66, in <module>
    from . import pygazebo
ImportError: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

**Comment by www2171668** [comment]
get the method in
http://blog.sina.com.cn/s/blog_54dd80920102v5js.html
and
https://www.it610.com/article/1188145227341340672.htm
