### ISSUE TITLE
ImportError: /usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name

### ISSUE THREAD

**Issue by YimiWangBJ** [HorizonRobotics/SocialRobot#80]
python3 python/social_bot/envs/grocery_ground.py
Traceback (most recent call last):
  File "python/social_bot/envs/grocery_ground.py", line 33, in <module>
    import social_bot
  File "/home/wangbingjie/anaconda3/lib/python3.5/site-packages/Repo_Root/python/social_bot/__init__.py", line 89, in <module>
    from . import pygazebo
ImportError: /usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name

**Comment by emailweixu** [comment]
Were you able to run gazebo itself?
